services:
  - type: web
    name: snippet-backend
    env: node
    plan: free
    rootDir: snippet/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GOOGLE_VISION_API_KEY
        sync: false

  - type: web
    name: snippet-frontend
    env: static
    plan: free
    rootDir: snippet/client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://snippet-backend.onrender.com 