services:
  - type: web
    name: podquote
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_BASE64
        sync: false 